/**
 * Builds `messages/car-products.fr.json` from `src/data/cars.ts` (French source)
 * and `messages/car-products.en.json` from the same data + `src/data/carEnglishContent.ts` overrides.
 *
 * For **es / de / pl**, reads existing `messages/car-products.{locale}.json` and **merges per slug**:
 * if a slug already differs from the freshly built English pack (localized description or richContent),
 * that entry is kept; otherwise it is replaced with the new English (so EN copy updates propagate until
 * you translate that slug — e.g. via `pnpm run bootstrap:car-products-locales` or hand-editing JSON).
 *
 * **Workflow (JSON-first):** edit `messages/car-products.es.json` (and de/pl) directly, or run the
 * bootstrap script once per locale family. Optional later: mirror `carEnglishContent.ts` with
 * `carSpanishContent.ts` etc. and extend this script to merge those overrides before the disk merge.
 *
 * Merged into next-intl `messages.carProducts` in `src/i18n/request.ts`.
 *
 * Usage: pnpm run generate:car-products
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getAllCars } from '../src/data/cars'
import { CAR_ENGLISH_BY_SLUG } from '../src/data/carEnglishContent'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

type ProductPack = { description: string; richContent?: unknown }

function stableStringify(value: unknown): string {
  if (value === null || typeof value !== 'object') {
    return JSON.stringify(value)
  }
  if (Array.isArray(value)) {
    return `[${value.map(stableStringify).join(',')}]`
  }
  const obj = value as Record<string, unknown>
  const keys = Object.keys(obj).sort()
  return `{${keys.map((k) => `${JSON.stringify(k)}:${stableStringify(obj[k])}`).join(',')}}`
}

/** True when `prev` should be kept instead of replacing with fresh `enPack`. */
function isLocalizedSecondary(prev: ProductPack | undefined, enPack: ProductPack): boolean {
  if (!prev?.description?.trim()) return false
  if (prev.description.trim() !== enPack.description.trim()) return true
  return stableStringify(prev.richContent) !== stableStringify(enPack.richContent)
}

function loadPreviousLocalePack(locale: 'es' | 'de' | 'pl'): Record<string, ProductPack> {
  const path = join(root, `messages/car-products.${locale}.json`)
  if (!existsSync(path)) return {}
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as Record<string, ProductPack>
  } catch {
    return {}
  }
}

function mergeSecondaryLocale(
  slugs: string[],
  en: Record<string, ProductPack>,
  locale: 'es' | 'de' | 'pl',
): Record<string, ProductPack> {
  const prev = loadPreviousLocalePack(locale)
  const out: Record<string, ProductPack> = {}
  for (const slug of slugs) {
    const enPack = en[slug]
    const p = prev[slug]
    out[slug] = isLocalizedSecondary(p, enPack) ? p! : enPack
  }
  return out
}

const fr: Record<string, ProductPack> = {}
const en: Record<string, ProductPack> = {}

for (const c of getAllCars()) {
  fr[c.slug] = {
    description: c.description,
    ...(c.richContent ? { richContent: c.richContent } : {}),
  }
  const o = CAR_ENGLISH_BY_SLUG[c.slug]
  en[c.slug] = {
    description: o?.description ?? c.description,
    richContent: o?.richContent ?? c.richContent,
  }
}

const slugs = getAllCars().map((c) => c.slug)

writeFileSync(join(root, 'messages/car-products.fr.json'), JSON.stringify(fr, null, 2) + '\n')
writeFileSync(join(root, 'messages/car-products.en.json'), JSON.stringify(en, null, 2) + '\n')

for (const locale of ['es', 'de', 'pl'] as const) {
  const merged = mergeSecondaryLocale(slugs, en, locale)
  writeFileSync(join(root, `messages/car-products.${locale}.json`), JSON.stringify(merged, null, 2) + '\n')
}

const slugsTs = `/**
 * Canonical French car slugs — auto-generated by npm run generate:car-products.
 * Used for locale switching on car detail URLs (FR vs EN slug segments).
 * Do not edit by hand.
 */
export const CAR_CANONICAL_SLUGS = ${JSON.stringify(slugs, null, 2)} as const

export type CarCanonicalSlug = (typeof CAR_CANONICAL_SLUGS)[number]
`
writeFileSync(join(root, 'src/data/carCanonicalSlugs.generated.ts'), slugsTs)

console.log(
  'Wrote messages/car-products.{fr,en,es,de,pl}.json (es/de/pl merged with prior localized slugs) and src/data/carCanonicalSlugs.generated.ts',
)
