/**
 * Builds `messages/car-products.fr.json` from `src/data/cars.ts` (French source)
 * and `messages/car-products.en.json` from the same data + `src/data/carEnglishContent.ts` overrides.
 * Merged into next-intl `messages.carProducts` in `src/i18n/request.ts`.
 *
 * Usage: npm run generate:car-products
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getAllCars } from '../src/data/cars'
import { CAR_ENGLISH_BY_SLUG } from '../src/data/carEnglishContent'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const fr: Record<string, { description: string; richContent?: unknown }> = {}
const en: Record<string, { description: string; richContent?: unknown }> = {}

for (const c of getAllCars()) {
  fr[c.slug] = {
    description: c.description,
    ...(c.richContent ? { richContent: c.richContent } : {}),
  }
  const o = CAR_ENGLISH_BY_SLUG[c.slug]
  en[c.slug] = {
    description: o?.description ?? c.description,
    richContent: o?.richContent ?? c.richContent,
  }
}

writeFileSync(join(root, 'messages/car-products.fr.json'), JSON.stringify(fr, null, 2) + '\n')
writeFileSync(join(root, 'messages/car-products.en.json'), JSON.stringify(en, null, 2) + '\n')

const slugs = getAllCars().map((c) => c.slug)
const slugsTs = `/**
 * Canonical French car slugs — auto-generated by npm run generate:car-products.
 * Used for locale switching on car detail URLs (FR vs EN slug segments).
 * Do not edit by hand.
 */
export const CAR_CANONICAL_SLUGS = ${JSON.stringify(slugs, null, 2)} as const

export type CarCanonicalSlug = (typeof CAR_CANONICAL_SLUGS)[number]
`
writeFileSync(join(root, 'src/data/carCanonicalSlugs.generated.ts'), slugsTs)

console.log(
  'Wrote messages/car-products.fr.json, messages/car-products.en.json, and src/data/carCanonicalSlugs.generated.ts',
)
