/**
 * Canonical French car slugs — auto-generated by npm run generate:car-products.
 * Used for locale switching on car detail URLs (FR vs EN slug segments).
 * Do not edit by hand.
 */
export const CAR_CANONICAL_SLUGS = [
  "location-voiture-agadir-bmw-x3-pack-m",
  "location-voiture-agadir-golf-8",
  "location-voiture-agadir-t-roc",
  "location-voiture-agadir-clio-5",
  "location-voiture-agadir-clio-5-blanche",
  "location-voiture-agadir-citroen-c4",
  "location-voiture-agadir-c3-aircross",
  "location-voiture-agadir-c3-aircross-gris",
  "location-voiture-agadir-citroen-c3",
  "location-voiture-agadir-hyundai-i10",
  "location-voiture-agadir-kia-picanto",
  "location-voiture-agadir-stepway",
  "location-voiture-agadir-sandero-stepway",
  "location-voiture-agadir-touareg",
  "location-voiture-agadir-dacia-logan",
  "location-voiture-agadir-kia-sportage",
  "location-voiture-agadir-kia-sportage-vert",
  "location-voiture-agadir-clio-5-gris",
  "location-voiture-agadir-kia-picanto-2025",
  "location-voiture-agadir-kia-picanto-noir",
  "location-voiture-agadir-kia-picanto-gris",
  "location-voiture-agadir-citroen-c3-2024",
  "location-voiture-agadir-dacia-logan-2026",
  "location-voiture-agadir-Clio-5-2025"
] as const

export type CarCanonicalSlug = (typeof CAR_CANONICAL_SLUGS)[number]
